import org.apache.hadoop.security.protocolPB.RefreshUserMappingsProtocolClientSideTranslatorPB;
public class FunctionUse17687 {
public void funcUse() {
RefreshUserMappingsProtocolClientSideTranslatorPB refreshusermappingsprotocolclientsidetranslatorpb = new RefreshUserMappingsProtocolClientSideTranslatorPB();
refreshusermappingsprotocolclientsidetranslatorpb.refreshUserToGroupsMappings();
}
}